### ISSUE TITLE
stop extensions like grammarly on the editor textarea

### ISSUE THREAD

**Issue by fdemir** [onderonur/code-image-generator#1]
## Expected behavior

Textarea code editor must not affect any observer from the extension. 

## Actual behavior

When Grammarly-like extensions are used, the extensions try to figure out grammatical errors in the code. 

## Steps to reproduce

1. Make sure you have installed the Grammarly etc. extension have installed
2. Go to the app
3. Paste a code

## Screenshots

![image](https://user-images.githubusercontent.com/48316033/226501415-03bfce17-aa26-4ebd-8b0d-58b912912e48.png)

## Possible Solutions

- Adding a data attr for grammarly only [https://github.com/jinjor/elm-break-dom/issues/27](https://github.com/jinjor/elm-break-dom/issues/27)
- Removing all mutation observers except highlighter or projects uses(recommended)

**Comment by onderonur** [comment]
First of all, thanks for creating this issue so clearly 🙏 

Since the `textbox` of the editor has `spellcheck="false"`, I'd expect those kind of extensions to ignore this field. But apparently they don't 🤔 

I don't think we should handle this on the project side, especially by adding custom/extension specific solutions like `data-*` attributes. There are lots of extensions (of course, Grammarly is one of the most popular ones) and we would end up wrestling with all those cases. I think it's up to users and they can switch the extension off for the sites they want.

I'll try to check the second (and also recommended) solution. I'm not sure if I understood it yet, but I will consider it.

Again, thanks for this clearly described issue 🙏
